### ISSUE TITLE
Remove from trustgroup script has syntax fail

### ISSUE THREAD

**Issue by morrowc** [ops-trust/portal#30]
morrowc@portal:~$ /proj/ops-trust/library/remove-from-tg bleepy@place.com TG
+ cd /proj/ops-trust/library
+ [ zbleepy@place.com == z -o zTG == z ]
/proj/ops-trust/library/remove-from-tg: 24: [: zbleepy@place.com: unexpected operator
+ psql -h db.ops-trust.net -p 5432 -d ops-trust
+ echo DELETE FROM member_trustgroup WHERE trustgroup='TG' AND email='bleepy@place.com';
Pager usage is off.
DELETE 1
+ exit

**Comment by massar** [comment]
Resolved with https://github.com/ops-trust/portal/commit/cc018294910753547ea53953dd73b47a4bd95ee4
