### ISSUE TITLE
Account details command

### ISSUE THREAD

**Issue by massar** [ops-trust/portal#34]
Currently for checking if somebody is locked out (password retry limit) and/or has 2FA enabled one has to check SQL. There should be a command and related web interface that allows checking these details.

**Comment by morrowc** [comment]
The command change is simple, I think... for findmember. The branch and pull request I think I can make happen shortly, but output:
$ /tmp/findmember morrow
[chrismorrow] 'Chris Morrow' 351b32a2-8e5b-11e0-9a24-dc106d20546d LA: 0 SF: TOTP
  [thingy] <morrowc@domain.net> active (person1, 3 years 6 mons 2 days)
  [blingy] <morrowc@domain.net> active (person2, 2 years 11 mons)
  [foobar] <morrowc@domain.net> active (person1, 2 years 6 mons 14 days)

**Comment by morrowc** [comment]
well crap... apparently I suck at git/github/merge/branch stuff :(
https://github.com/ops-trust/portal/commit/583edd66176893874c0dd673820f60d91d023c80

is the commit that does the above update's magic.

**Comment by morrowc** [comment]
If the above looks good, feel free to close the issue.

**Comment by massar** [comment]
That solves it quite fine! Closing this ticket.
