### ISSUE TITLE
Missing funcs.sh

### ISSUE THREAD

**Issue by wfms** [ops-trust/portal#43]
When doing a make install after a make on the portal code, the following is displayed at the end:

/proj/ops-trust/library/fix-install: 22: .: Can't open ./funcs.sh
make: *** [install] Error 2

Doesn't seem to be anywhere in the code tree.

**Comment by massar** [comment]
Install did not install it, resolved in:

https://github.com/ops-trust/portal/commit/4d480144a7adf03fd1f0dd38e3969d0fef97361d
